Face Recognition

In [3]:
from PIL import Image
from tensorflow.keras.applications.inception_resnet_v2 import preprocess_input

import cv2
from tensorflow.keras.models import load_model
import numpy as np

from tensorflow.keras.preprocessing import image
model = load_model('facefeatures_model.h5')

classifier = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

def extractor(image):
        
    faces = classifier.detectMultiScale(image, 1.3, 5)
    
    if faces is ():
        return None
    
    for (x,y,w,h) in faces:
        cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,255),2)
        new_cropped_face = image[y:y+h, x:x+w]

    return new_cropped_face

video_capture = cv2.VideoCapture(0)
while True:
    return_value, frame_captured = video_capture.read()
    
    
    face=extractor(frame_captured)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')
        image_array = np.array(im)
                   
        image_array = np.expand_dims(image_array, axis=0)
        prediction = model.predict(image_array)
        print(prediction)
                     
        name="None matching"
        
        if(prediction[0][0]>0.5):
            name='Akshay Kumar'
        elif(prediction[0][1]>0.5):
            name='Barack Obama'
        elif(prediction[0][2]>0.5):
            name='Dhruv'
        elif(prediction[0][3]>0.5):
            name='Donald Trump'
        elif(prediction[0][4]>0.5):
            name='Elon Musk'
        elif(prediction[0][5]>0.5):
            name='Jeff Bezos'
        elif(prediction[0][6]>0.5):
            name='Sachin Tendulkar'
        cv2.putText(frame_captured,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)

#         if(prediction[:,0]>=0.5):
#             name='Akshay Kumar'
#             cv2.putText(frame_captured,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
#         elif(prediction[:,1]>=0.5):
#             name='Barack Obama'
#             cv2.putText(frame_captured,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
#         elif(prediction[:,2]>=0.5):
#             name='Dhruv'
#             cv2.putText(frame_captured,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
#         elif(prediction[:,3]>=0.5):
#             name='Donald Trump'
#             cv2.putText(frame_captured,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
#         elif(prediction[:,4]>=0.5):
#             name='Elon Musk'
#             cv2.putText(frame_captured,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
#         elif(prediction[:,5]>=0.5):
#             name='Jeff Bezos'
#             cv2.putText(frame_captured,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
#         elif(prediction[:,6]>=0.5):
#             name='Sachin Tendulkar'
#             cv2.putText(frame_captured,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    
    
    else:
        cv2.putText(frame_captured,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', frame_captured)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 1. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 1.]]
